Add tests to verify if $all position is populated when reading stream
EventStore/EventStoreDB-Client-Rust pull request #152
Opened 2022-07-18 09:04 UTC by shaan1337

Context: https://github.com/EventStore/EventStore/pull/3459

2022-07-18 13:21 UTC, YoEight requested changes

2022-07-19 05:52 UTC, shaan1337 commented on eventstore/tests/integration.rs
> +    test_read_stream_populates_log_position(&client).await?;
fixed, thanks!

2022-07-19 09:46 UTC, thefringeninja approved these changes

2022-07-19 12:10 UTC, YoEight approved these changes

2022-07-19 12:10 UTC, merged