update to tonic 0.9
EventStore/EventStoreDB-Client-Rust pull request #162
Opened 2023-06-05 06:05 UTC by henriiik

Hello! Here comes a small PR that updates tonic to the latest version. :)

2023-07-06 14:13 UTC, YoEight commented
@henriiik First of all, I'm sorry I just saw that PR!

I turned off notification on that repo by mistake.

2023-07-06 14:20 UTC, YoEight requested changes
Thanks again for your contribution!

I do believe it would be safer to regenerate the grpc code. You can achieve that by uncommenting the property `build` in the client Cargo.toml file. When you are done, comment it back.

2023-07-06 14:20 UTC, YoEight commented on CHANGELOG.md
> +- Update to tonic 0.9  [EventStoreDB-Client-Rust#162](https://github.com/EventStore/EventStoreDB-Client-Rust/pull/162)
You don't need to update this file, it will be done automatically by one of our bots.

2023-07-07 14:19 UTC, henriiik commented
@YoEight thanks for the feedback! I have regenerated the GRPC code and removed the entry from the changelog.

2023-07-10 12:53 UTC, YoEight approved these changes
Nice work!

2023-07-10 12:54 UTC, merged