Split delete_stream and tombstone_stream
EventStore/EventStoreDB-Client-Rust pull request #84
Opened 2021-08-20 09:19 UTC by arwinneil

Related to https://github.com/EventStore/EventStoreDB-Client-Rust/issues/79

2021-08-20 14:05 UTC, YoEight requested changes
Please run `cargo fmt`, because the code won't pass the linting phase.

2021-08-20 16:08 UTC, arwinneil commented
@YoEight Formatted code and squashed commits. 👍

2021-08-21 21:59 UTC, YoEight commented
You might consider rebasing from #85 to fix the projection tests flakiness you are experiencing

2021-08-23 09:23 UTC, thefringeninja approved these changes

2021-08-24 13:56 UTC, YoEight approved these changes

2021-08-24 13:57 UTC, YoEight approved these changes

2021-08-24 13:58 UTC, merged